// Code generated by options-gen. DO NOT EDIT.
package app

import (
	"net/http"
	"time"

	"github.com/google/go-github/v48/github"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	options ...OptOptionsSetter,
) Options {
	o := Options{}

	// Setting defaults from variable
	o.responseHttpClient = defaultOptions.responseHttpClient
	o.responseTimeout = defaultOptions.responseTimeout
	o.githubClient = defaultOptions.githubClient

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithResponseHttpClient(opt *http.Client) OptOptionsSetter {
	return func(o *Options) {
		o.responseHttpClient = opt
	}
}

func WithResponseTimeout(opt time.Duration) OptOptionsSetter {
	return func(o *Options) {
		o.responseTimeout = opt
	}
}

func WithGithubClient(opt *github.Client) OptOptionsSetter {
	return func(o *Options) {
		o.githubClient = opt
	}
}

func (o *Options) Validate() error {
	return nil
}
