// Code generated by options-gen. DO NOT EDIT.
package app

import (
	"time"

	"github.com/google/go-github/v48/github"
	"github.com/kazhuravlev/awesome-tool/pkg/httph"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	options ...OptOptionsSetter,
) Options {
	o := Options{}

	// Setting defaults from variable
	o.responseTimeout = defaultOptions.responseTimeout
	o.githubClient = defaultOptions.githubClient
	o.http = defaultOptions.http
	o.maxWorkers = defaultOptions.maxWorkers

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithResponseTimeout(opt time.Duration) OptOptionsSetter {
	return func(o *Options) {
		o.responseTimeout = opt
	}
}

func WithGithubClient(opt *github.Client) OptOptionsSetter {
	return func(o *Options) {
		o.githubClient = opt
	}
}

func WithHttp(opt *httph.Client) OptOptionsSetter {
	return func(o *Options) {
		o.http = opt
	}
}

func WithMaxWorkers(opt int) OptOptionsSetter {
	return func(o *Options) {
		o.maxWorkers = opt
	}
}

func (o *Options) Validate() error {
	return nil
}
