// Code generated by options-gen. DO NOT EDIT.
package httph

import (
	"net/http"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	options ...OptOptionsSetter,
) Options {
	o := Options{}

	// Setting defaults from variable
	o.client = defaultOptions.client
	o.maxEquivRedirects = defaultOptions.maxEquivRedirects

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithClient(opt *http.Client) OptOptionsSetter {
	return func(o *Options) {
		o.client = opt
	}
}

func WithMaxEquivRedirects(opt int) OptOptionsSetter {
	return func(o *Options) {
		o.maxEquivRedirects = opt
	}
}

func (o *Options) Validate() error {
	return nil
}
